### ISSUE TITLE
1.18.2 fabric can't spawn the wandering trapper

### ISSUE THREAD

**Issue by StaddyBigDaddy** [lilypuree/WanderingTrapper#11]
[19:15:12] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@13fb2c59, suppressing error
java.lang.NullPointerException: Cannot invoke "lilypuree.wandering_trapper.compat.IWeaponSelector.getMoveSpeedAmp()" because "selector" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at lilypuree.wandering_trapper.entity.ai.CustomRangedAttackGoal.<init>(CustomRangedAttackGoal.java:30) ~[Wandering+Trapper-fabric-1.18.2-1.2.0.jar:?]
	at lilypuree.wandering_trapper.entity.WanderingTrapperEntity.initGoals(WanderingTrapperEntity.java:72) ~[Wandering+Trapper-fabric-1.18.2-1.2.0.jar:?]
	at net.minecraft.entity.mob.MobEntity.<init>(MobEntity:144) ~[?:?]
	at net.minecraft.entity.mob.PathAwareEntity.<init>(PathAwareEntity:14) ~[?:?]
	at net.minecraft.entity.passive.PassiveEntity.<init>(PassiveEntity:28) ~[?:?]
	at net.minecraft.entity.passive.MerchantEntity.<init>(MerchantEntity:55) ~[?:?]
	at lilypuree.wandering_trapper.entity.WanderingTrapperEntity.<init>(WanderingTrapperEntity.java:59) ~[Wandering+Trapper-fabric-1.18.2-1.2.0.jar:?]
	at net.minecraft.entity.EntityType.create(EntityType:478) ~[?:?]
	at net.minecraft.entity.EntityType.create(EntityType:347) ~[?:?]
	at net.minecraft.entity.EntityType.spawn(EntityType:335) ~[?:?]
	at net.minecraft.entity.EntityType.spawnFromItemStack(EntityType:326) ~[?:?]
	at lilypuree.wandering_trapper.item.WanderingTrapperSpawnEgg.useOnBlock(WanderingTrapperSpawnEgg.java:64) ~[Wandering+Trapper-fabric-1.18.2-1.2.0.jar:?]
	at net.minecraft.item.ItemStack.useOnBlock(ItemStack:250) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:353) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by StaddyBigDaddy** [comment]
It says unable to summon entity whenever i try to summon a wandering trapper, or any wolf

**Comment by StaddyBigDaddy** [comment]
i found that the wolfs fix when removing W.O.L.F mod and the traders fix when removing  ewewukek's musket mod
https://www.curseforge.com/minecraft/mc-mods/ewewukeks-musket-mod
https://www.curseforge.com/minecraft/mc-mods/woof
is this able to be fixed?

**Comment by lilypuree** [comment]
Ewewukek's musket mod isn't updated to 1.18.2, woof is a known incompatibility

**Comment by StaddyBigDaddy** [comment]
oh i see, there is a port someone has made for 1.18.2 in the comment section of the mod that i didn't realise i had downloaded, is it possible to add compatibility for that version while we for the actual mod to be updated?
heres the link if you need it: https://drive.google.com/file/d/1D5lEiMNn5ouv4RHJeHpyUhSob_GfAXUC/view
